### ISSUE TITLE
JSON Decode error

### ISSUE THREAD

**Issue by BatmanGotham** [hackingthemarkets/iex-cloud-dashboard#1]
Traceback (most recent call last):
  File "C:\Users\user\Desktop\jiaeek\iex-cloud-dashboard-main\dashboard.py", line 82, in <module>
    stats = stock.get_stats()
  File "C:\Users\user\Desktop\jiaeek\iex-cloud-dashboard-main\iex.py", line 36, in get_stats
    return r.json()
  File "C:\Users\user\Desktop\jiaeek\iex-cloud-dashboard-main\venv\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by TomNewton1** [comment]
I believe this error occurs when trying to access JSON data from the **advanced-stats** URL. This feature is only included in with paid subscription plans. 

You can substitute the advanced-stats url with key stats using the following: 

GET /stock/{symbol}/stats/{stat?}

Also possible that the IEX api does't have information on the stock you are requesting.

**Comment by jpcam** [comment]
I found this error pop up any time there is an unresolved ticker requested to the api. The file you get back is blank.
Many things can cause this including not having the correct suffix for a non-US stock or trying to access a data end point that does not exist for a particular stock. These are trickier to resolve. However another common fix is to get a new api token (yours might be spent) and move out of the sandbox, the sandbox seems to have less data in some cases.
